### PR TITLE
loosen toolset restriction

### PR DESCRIPTION
**Pull request by cbouss**
vs2022 toolsets are in the 14.40 serie. A recent update on the builder installed toolset 14.42 instead of previous 14.41.
Setting -vcvars_ver=14.4 correctly results in VCToolsVersion=14.42.34433

### CODE REVIEW

**Review by danpetry — COMMENTED** [review]
It looks like the vcruntime was also updated.

You could also set the tools_version in the cbc to 14.4 and use %tools_version% in the bat scripts.

**Comment by danpetry** [comment]
Is it necessary for the vcruntime140.dll version to be so restrictive, too?

**Comment by cbouss** [comment]
> Is it necessary for the vcruntime140.dll version to be so restrictive, too?

There is a ticket for a revamp of this feedstock which could help achieving this without a hardcoded path. 
For now that will do.

**Review by bwingconda — APPROVED** [review]

**Comment by danpetry** [comment]
Probably a good idea to compile something with this before merging?

**Comment by danpetry** [comment]
This may be being used outside Anaconda..

**Comment by cbouss** [comment]
Tested working on a local build.

**Review by danpetry — APPROVED** [review]

**Pull request merged**
